server:
  address: 0.0.0.0   # ✅ Listen on all interfaces
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://192.168.1.203:5432/authdb
    username: TravelApplication123
    password: TravelApplication123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 15000

services:
  employee:
    url: http://BWC-97.brainwaveconsulting.co.in:8080/ems   # ✅ correct indentation

jwt:
  secret: MySuperSecureAesEncryptionKey123456   # ✅ MATCHES gateway
  expiration-seconds: 3600
