# =========================================================
# 🌍 Application Info
# =========================================================
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      # ✅ Global CORS configuration (frontend + local dev)
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://bwc-90.brainwaveconsulting.co.in:3000"
              - "http://bwc-90.brainwaveconsulting.co.in:3001"
            allowedMethods: [GET, POST, PUT, DELETE, OPTIONS]
            allowedHeaders: "*"
            exposedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true

      # ✅ ROUTES CONFIGURATION
      routes:
        - id: employee-service
          uri: http://localhost:9010
          predicates:
            - Path=/ems/**
          filters:
            - AddRequestHeader=X-Internal-Gateway-Secret, bwc-secure-gateway

        - id: auth-service
          uri: http://localhost:9011
          predicates:
            - Path=/auth/**
          filters:
            - AddRequestHeader=X-Internal-Gateway-Secret, bwc-secure-gateway

        - id: policy-service
          uri: http://localhost:9012
          predicates:
            - Path=/policy/**
          filters:
            - AddRequestHeader=X-Internal-Gateway-Secret, bwc-secure-gateway

        - id: workflow-service
          uri: http://localhost:9013
          predicates:
            - Path=/workflow/**
          filters:
            - AddRequestHeader=X-Internal-Gateway-Secret, bwc-secure-gateway

        - id: notification-service
          uri: http://localhost:9014
          predicates:
            - Path=/notification/**
          filters:
            - AddRequestHeader=X-Internal-Gateway-Secret, bwc-secure-gateway

        - id: travel-request-management
          uri: http://localhost:9015
          predicates:
            - Path=/travel-management/**
          filters:
            - AddRequestHeader=X-Internal-Gateway-Secret, bwc-secure-gateway

      # 🧱 Remove unsafe headers before forwarding
      default-filters:
        - RemoveRequestHeader=Connection
        - RemoveRequestHeader=Keep-Alive
        - RemoveRequestHeader=Transfer-Encoding
        - RemoveRequestHeader=TE
        - RemoveRequestHeader=Trailer
        - RemoveRequestHeader=Upgrade
        - RemoveRequestHeader=Proxy-Authorization

      # ⚙️ Enable response time tracing & detailed metrics
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s
        pool:
          type: elastic
          max-connections: 2000
          max-idle-time: 60s

# =========================================================
# ⚙️ Server Configuration
# =========================================================
server:
  address: 0.0.0.0
  port: 9016
  tomcat:
    connection-timeout: 10s     # ✅ Fixed: moved under tomcat (no deprecation)
    max-threads: 300
    min-spare-threads: 20
    accept-count: 300
    max-connections: 5000

# =========================================================
# 🔐 Security / JWT Config
# =========================================================
jwt:
  secret: MySuperSecureAesEncryptionKey123456
  expiration-seconds: 3600

# =========================================================
# 🔑 Internal Gateway Shared Secret
# =========================================================
gateway:
  internal:
    secret: bwc-secure-gateway

# =========================================================
# 🧾 Logging
# =========================================================
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.web.reactive: INFO
    org.springframework.http.server.reactive: INFO
    com.bwc.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/api-gateway.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10

# =========================================================
# 📊 Actuator
# =========================================================
management:
  server:
    port: 9116
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,threaddump,heapdump
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    env:
      enabled: true
